import type { PyqQuestion, PyqSubject } from '@/types/pyq'

type Rule = [label: string, pattern: RegExp]

const RULES: Record<PyqSubject, Rule[]> = {
  'Ancient History': [
    ['Prehistory and Archaeology', /prehistor|palaeolith|mesolith|neolith|chalcolith|archaeolog/i],
    ['Indus Valley Civilisation', /harapp|indus valley|mohenjo|dholavira|lothal|kalibangan/i],
    ['Vedic Age', /vedic|rig veda|samaveda|yajurveda|atharva|upanishad/i],
    ['Mahajanapadas and Early States', /mahajanapada|magadha|bimbisara|ajatasatru|nanda/i],
    ['Buddhism and Jainism', /buddh|jain|tirthankara|mahavira|tripitaka|sangha/i],
    ['Mauryan Empire', /maurya|ashoka|kautilya|arthashastra|megasthe/i],
    ['Post-Mauryan India', /kushana|satavahana|shaka|indo-greek|kanishka/i],
    ['Gupta Age', /gupta|samudragupta|chandragupta|aryabhatta|fa-hien/i],
    ['Sangam and South India', /sangam|chola|chera|pandya|pallava/i],
    ['Ancient Literature and Sources', /inscription|edict|chronicle|literature|text|author|traveller/i],
  ],
  'Medieval History': [
    ['Early Medieval and Regional Kingdoms', /early medieval|rajput|pala|pratihara|rashtrakuta|regional kingdom/i],
    ['Delhi Sultanate', /sultanate|slave dynasty|khilji|tughlaq|sayyid|lodi|balban|iltutmish/i],
    ['Vijayanagara and Bahmani Kingdoms', /vijayanagara|bahmani|krishnadevaraya|hampi/i],
    ['Bhakti and Sufi Traditions', /bhakti|sufi|kabir|nanak|chaitanya|nizamuddin|khwaja/i],
    ['Mughal Empire', /mughal|babur|humayun|akbar|jahangir|shah jahan|aurangzeb/i],
    ['Marathas and Later Medieval India', /maratha|shivaji|peshwa|ashtapradhan/i],
    ['Medieval Administration and Economy', /mansab|jagir|iqta|revenue|administration|market/i],
    ['Medieval Art and Culture', /architecture|painting|music|literature|monument|temple/i],
  ],
  'Modern History': [
    ['European Entry into India', /portuguese|dutch|french|european|east india compan/i],
    ['British Expansion and Consolidation', /plassey|buxar|subsidiary alliance|doctrine of lapse|annex/i],
    ['Colonial Economy and Land Revenue', /permanent settlement|ryotwari|mahalwari|drain of wealth|deindustr/i],
    ['Revolt of 1857', /1857|sepoy mutiny|revolt/i],
    ['Socio-Religious Reform Movements', /brahmo|arya samaj|rammohan|vidyasagar|aligarh|reform movement/i],
    ['Peasant and Tribal Movements', /peasant|tribal|santhal|munda|indigo|tebhaga|bardoli/i],
    ['Early Nationalism and Swadeshi', /moderate|extremist|swadeshi|surat split|home rule|partition of bengal/i],
    ['Gandhian Era and Mass Movements', /gandhi|non-cooperation|civil disobedience|quit india|satyagraha/i],
    ['Revolutionary Movement and INA', /revolutionar|ghadar|kakori|bhagat singh|subhas|ina|azad hind/i],
    ['Constitutional Developments', /charter act|council act|government of india act|cabinet mission|cripps|mountbatten/i],
    ['Press, Education and Associations', /newspaper|journal|press|education|university|association|sabha/i],
    ['National Movement Personalities', /viceroy|governor-general|nationalist|leader|president of congress/i],
  ],
  'Art and Culture': [
    ['Indian Architecture', /architecture|stupa|cave|fort|palace|rock-cut/i],
    ['Temple Architecture', /temple|nagara|dravida|vesara|gopuram|shikhara/i],
    ['Sculpture and Iconography', /sculpture|statue|bronze|iconograph|mudra/i],
    ['Indian Painting', /painting|miniature|mural|kalamkari|madhubani|pattachitra/i],
    ['Classical and Folk Dance', /dance|bharatanatyam|kathak|kuchipudi|odissi|yakshagana/i],
    ['Music Traditions', /music|raga|gharana|instrument|carnatic|hindustani/i],
    ['Literature and Languages', /literature|language|poet|author|text|sanskrit|tamil/i],
    ['Religion and Philosophy', /philosophy|school of thought|vedanta|yoga|buddh|jain/i],
    ['Fairs, Festivals and Traditions', /festival|fair|tradition|craft|puppet|martial art/i],
  ],
  Polity: [
    ['Constitutional History', /regulating act|charter act|government of india act|constituent assembly|historical background/i],
    ['Preamble and Basic Structure', /preamble|basic structure|kesavananda/i],
    ['Fundamental Rights', /fundamental right|article 1[23456789]|writ|freedom of|right to/i],
    ['Directive Principles', /directive principle|dpsp|article 3[6-9]|article 4[0-9]/i],
    ['Fundamental Duties', /fundamental dut|article 51a/i],
    ['Citizenship', /citizenship|citizen|naturalisation|overseas citizen/i],
    ['President and Vice-President', /president|vice-president|electoral college|impeach/i],
    ['Prime Minister and Council of Ministers', /prime minister|council of ministers|cabinet|collective responsibil/i],
    ['Parliament and Legislative Procedure', /parliament|lok sabha|rajya sabha|speaker|bill|money bill|committee/i],
    ['Supreme Court and High Courts', /supreme court|high court|chief justice|judge|collegium/i],
    ['Judicial Review and Tribunals', /judicial review|tribunal|public interest litigation|pil/i],
    ['Centre-State Relations and Federalism', /centre-state|federal|inter-state|union list|state list|concurrent/i],
    ['Governor and State Executive', /governor|chief minister|state executive/i],
    ['State Legislature', /state legislature|legislative council|vidhan/i],
    ['Local Government', /panchayat|municipal|gram sabha|local government|73rd|74th/i],
    ['Emergency Provisions', /emergency|article 352|article 356|article 360|president.?s rule/i],
    ['Constitutional and Statutory Bodies', /election commission|finance commission|cag|upsc|nhrc|commission/i],
    ['Elections and Anti-Defection', /election|anti-defection|tenth schedule|political party/i],
    ['Amendment, Schedules and Special Provisions', /amendment|schedule|special provision|article 370|fifth schedule|sixth schedule/i],
    ['Governance, Transparency and Accountability', /governance|rti|lokpal|accountability|civil service/i],
  ],
  Economy: [
    ['National Income and Growth', /gdp|gva|national income|economic growth|per capita/i],
    ['Inflation and Business Cycles', /inflation|deflation|stagflation|cpi|wpi|business cycle/i],
    ['Monetary Policy and RBI', /rbi|monetary policy|repo|crr|slr|money supply|liquidity/i],
    ['Banking and Financial Institutions', /bank|nbfc|npa|deposit|credit|financial institution/i],
    ['Fiscal Policy and Public Finance', /fiscal|budget|deficit|public debt|government expenditure/i],
    ['Taxation and GST', /tax|gst|cess|customs|income tax/i],
    ['External Sector and Balance of Payments', /balance of payment|current account|exchange rate|forex|capital account/i],
    ['International Trade and WTO', /trade|export|import|tariff|wto|free trade/i],
    ['Capital and Securities Markets', /stock|share|bond|sebi|capital market|mutual fund|sensex/i],
    ['Agriculture and Food Management', /agriculture|crop|msp|food corporation|buffer stock|pds/i],
    ['Industry and Infrastructure', /industry|manufactur|infrastructure|core sector|industrial policy/i],
    ['Employment, Poverty and Inequality', /employment|unemployment|poverty|inequality|labour/i],
    ['Planning and Economic Reforms', /planning|five year plan|liberalisation|privatisation|economic reform/i],
    ['Digital Economy and Payments', /upi|digital|cryptocurrency|fintech|payment/i],
    ['Sustainable Development', /sustainable development|green economy|circular economy|carbon market/i],
    ['Reports, Indices and Institutions', /report|index|world bank|imf|adb|niti aayog/i],
  ],
  Geography: [
    ['Geomorphology and Earth Interior', /plate tectonic|earthquake|volcano|rock|landform|geomorph|interior of earth/i],
    ['Climatology and Atmosphere', /climate|atmosphere|temperature|pressure|wind|jet stream/i],
    ['Indian Monsoon', /monsoon|western disturbance|el nino|la nina|iod/i],
    ['Oceanography', /ocean|current|tide|coral|salinity|upwelling/i],
    ['Rivers and Drainage', /river|drainage|tributary|delta|estuary|basin/i],
    ['Mountains, Plateaus and Plains', /mountain|himalaya|plateau|plain|range|peak/i],
    ['Soils and Natural Vegetation', /soil|vegetation|forest type/i],
    ['Agricultural Geography', /crop|agriculture|irrigation|plantation/i],
    ['Minerals and Energy Resources', /mineral|coal|petroleum|natural gas|ore|energy resource/i],
    ['Population and Human Geography', /population|migration|settlement|urban|demograph/i],
    ['Industries and Transport', /industry|industrial region|transport|port|corridor/i],
    ['India Map-Based Geography', /india|state|district|indian map|location/i],
    ['World Map-Based Geography', /country|continent|world map|sea|strait|island/i],
    ['Solar System and Earth Evolution', /solar system|planet|sun|earth evolution|astronom/i],
  ],
  Environment: [
    ['Ecology and Ecosystems', /ecology|ecosystem|food chain|food web|ecological pyramid/i],
    ['Biodiversity and Conservation', /biodiversity|conservation|endem|hotspot/i],
    ['Species in News', /species|iucn|animal|bird|plant|mammal|reptile/i],
    ['Protected Areas', /national park|wildlife sanctuary|biosphere reserve|tiger reserve|protected area/i],
    ['Climate Change', /climate change|global warming|greenhouse gas|carbon emission|unfccc|cop\d/i],
    ['Pollution and Waste Management', /pollution|waste|effluent|plastic|particulate|sewage/i],
    ['Environmental Laws and Institutions', /environment act|wildlife protection|forest conservation|tribunal|ngt/i],
    ['International Environmental Conventions', /convention|protocol|ramsar|cites|cbd|montreal/i],
    ['Forests and Afforestation', /forest|afforestation|deforestation|mangrove/i],
    ['Wetlands and Coastal Ecosystems', /wetland|ramsar|coastal|mangrove|estuary/i],
    ['Agriculture and Environment', /agriculture|fertiliser|pesticide|organic farming|soil/i],
    ['Renewable Energy and Green Technology', /renewable|solar|wind energy|biofuel|hydrogen|green technology/i],
    ['Environmental Impact Assessment', /environmental impact|eia|clearance/i],
  ],
  'Science and Tech': [
    ['Space Technology', /space|satellite|orbit|rocket|isro|planetary mission/i],
    ['Defence Technology', /missile|defence|radar|submarine|weapon|drone|uav/i],
    ['Biotechnology and Genetic Engineering', /biotech|gene|dna|rna|genetic|crispr|genome/i],
    ['Human Health and Diseases', /disease|virus|bacteria|vaccine|antibody|health|pathogen/i],
    ['Cell Biology and Physiology', /cell|protein|enzyme|hormone|organ|physiology/i],
    ['Information Technology and Computing', /computer|internet|artificial intelligence|machine learning|quantum comput|semiconductor/i],
    ['Communication Technology', /telecom|5g|communication|spectrum|radio wave/i],
    ['Robotics and Emerging Technology', /robot|drone|uav|3d print|nanotech/i],
    ['Energy Technology', /battery|fuel cell|nuclear|fusion|fission|hydrogen/i],
    ['Physics', /photon|laser|wave|electric|magnet|radiation|physics/i],
    ['Chemistry and Materials', /chemical|element|compound|polymer|catalyst|material/i],
    ['Agricultural and Food Technology', /crop|seed|food technology|biofortif|genetically modified/i],
    ['Intellectual Property and Technology Policy', /patent|copyright|intellectual property|technology policy/i],
  ],
  'International Relations': [
    ['India and Its Neighbourhood', /china|pakistan|bangladesh|nepal|bhutan|sri lanka|myanmar|maldives/i],
    ['India and Major Powers', /united states|usa|russia|france|japan|european union|uk\b/i],
    ['International Organisations', /united nations|un\b|wto|imf|world bank|who|unesco|international organisation/i],
    ['Regional and Strategic Groupings', /brics|quad|sco|asean|g20|g7|bimstec|saarc/i],
    ['Treaties and International Law', /treaty|convention|international law|agreement|protocol/i],
    ['Security and Geopolitics', /security|geopolit|conflict|war|terror|nuclear/i],
    ['Trade and Economic Diplomacy', /trade|corridor|investment|economic partnership/i],
    ['Maritime and Indo-Pacific', /indo-pacific|maritime|ocean|strait|sea|port/i],
    ['Global Issues and Diplomacy', /climate|migration|humanitarian|diplomacy|global/i],
  ],
  'Current Affairs': [
    ['Government Schemes and Initiatives', /scheme|mission|initiative|yojana|programme|ministry/i],
    ['Reports and Indices', /report|index|ranking|survey/i],
    ['National Institutions and Appointments', /appointed|chairperson|commission|institution|authority/i],
    ['International Events and Organisations', /international|summit|organisation|country|united nations/i],
    ['Awards, Culture and Personalities', /award|prize|personality|author|film|festival/i],
    ['Sports', /sport|games|championship|tournament|olympic/i],
    ['Places and Events in News', /location|place|city|state|disaster|event/i],
    ['Science, Economy and Policy in News', /technology|economy|policy|bill|act|launch/i],
  ],
}

function cleanSourceTopic(topic: string) {
  return topic
    .replace(/\s+Pw Onlyias.*$/i, '')
    .replace(/^Bmw Ag Usa$/i, '')
    .replace(/\s+/g, ' ')
    .trim()
}

export function getPyqSubtopic(question: Pick<PyqQuestion, 'subject' | 'topic' | 'stem' | 'options' | 'tags'>) {
  const sourceTopic = cleanSourceTopic(question.topic)
  const text = [question.stem, ...(question.options ?? []), ...question.tags, sourceTopic].join(' ')
  const inferred = RULES[question.subject]?.find(([, pattern]) => pattern.test(text))?.[0]
  const broad = !sourceTopic || sourceTopic.toLowerCase() === question.subject.toLowerCase() || /^(miscellaneous|current affairs)$/i.test(sourceTopic)
  return inferred ?? (!broad ? sourceTopic : `${question.subject} Fundamentals`)
}
